on:
  push:
    branches:
      - main
    paths:
      - api-server/**
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: api-server/

jobs:
  build:
    uses: Implex1v/go-todo-app/.github/workflows/_build.yml@main
    with:
      component: api-server
